<a href="https://colab.research.google.com/github/Oluwatobi50/Internship-program/blob/master/Copy_of_Untitled4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

/usr/local/lib/python3.6/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


In [ ]:
A = [1,2,3,4,5,6] 
B = [13,21,34]
C = A+B
print (C)

[1, 2, 3, 4, 5, 6, 13, 21, 34]


In [ ]:
A_B = A.extend(B)
print(A_B)

None


In [ ]:
import numpy as np

In [ ]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
url = 'https://raw.githubusercontent.com/WalePhenomenon/climate_change/master/fuel_ferc1.csv'
fuel_df = pd.read_csv(url, error_bad_lines =False)
fuel_df.head(5)

record_id  ...  fuel_cost_per_mmbtu
0   f1_fuel_1994_12_1_0_7  ...                1.121
1  f1_fuel_1994_12_1_0_10  ...                1.120
2   f1_fuel_1994_12_2_0_1  ...                1.650
3   f1_fuel_1994_12_2_0_7  ...                1.970
4  f1_fuel_1994_12_2_0_10  ...                2.570

[5 rows x 11 columns]

In [ ]:
#fuel type with the lowest fuel cost per unit burned
fuel_df.columns

Index(['record_id', 'utility_id_ferc1', 'report_year', 'plant_name_ferc1',
       'fuel_type_code_pudl', 'fuel_unit', 'fuel_qty_burned',
       'fuel_mmbtu_per_unit', 'fuel_cost_per_unit_burned',
       'fuel_cost_per_unit_delivered', 'fuel_cost_per_mmbtu'],
      dtype='object')

In [ ]:
fuel_df.groupby('fuel_type_code_pudl')['fuel_cost_per_unit_burned'].mean()

fuel_type_code_pudl
coal         67.421830
gas          13.659397
nuclear    4955.157002
oil         168.877086
other        18.253856
waste        19.518122
Name: fuel_cost_per_unit_burned, dtype: float64

In [ ]:
#get standard deviation and 75 percentile of fuel_mmbtu_per_unit
describe = fuel_df['fuel_mmbtu_per_unit'].describe()
describe.round(2)

count    29523.00
mean         8.49
std         10.60
min          0.00
25%          1.02
50%          5.76
75%         17.01
max        341.26
Name: fuel_mmbtu_per_unit, dtype: float64

In [ ]:
#find skewness of fuel_qty_burned
skew = fuel_df['fuel_qty_burned'].skew()
skew.round(2)

15.85

In [ ]:
#find kurtosis of fuel_qty_burned
kurt = fuel_df['fuel_qty_burned'].kurt()
kurt.round(2)

651.37

In [ ]:
#find the column with missing values
fuel_df.isnull().sum()

record_id                         0
utility_id_ferc1                  0
report_year                       0
plant_name_ferc1                  0
fuel_type_code_pudl               0
fuel_unit                       180
fuel_qty_burned                   0
fuel_mmbtu_per_unit               0
fuel_cost_per_unit_burned         0
fuel_cost_per_unit_delivered      0
fuel_cost_per_mmbtu               0
dtype: int64

In [ ]:
#total number of missing values in the fuel_unit column
fuel_df['fuel_unit'].isnull().sum()

180

In [ ]:
#percentage of missing values with total number of rows
percent_null=((fuel_df['fuel_unit'].isnull().sum())/len(fuel_df))*100
percent_null.round(3)

0.61

In [ ]:
#find data type of fuel_unit column and method of imputation for the missing values
fuel_df.groupby('fuel_unit')['fuel_unit'].count()

fuel_unit
bbl        7998
gal          84
gramsU      464
kgU         110
mcf       11354
mmbtu       180
mwdth        95
mwhth       100
ton        8958
Name: fuel_unit, dtype: int64

In [ ]:
#find the second and third lowest correlation with fuel_cost_per_unit_burned
corr = fuel_df.corr()
corr['fuel_cost_per_unit_burned']

utility_id_ferc1               -0.037863
report_year                     0.013599
fuel_qty_burned                -0.018535
fuel_mmbtu_per_unit            -0.010034
fuel_cost_per_unit_burned       1.000000
fuel_cost_per_unit_delivered    0.011007
fuel_cost_per_mmbtu            -0.000437
Name: fuel_cost_per_unit_burned, dtype: float64

In [ ]:
fuel_burned_cost = fuel_df.groupby(['report_year','fuel_type_code_pudl'])['fuel_cost_per_unit_burned'].sum()
fuel_burned_cost 
#fuel_burned_cost['fuel_type_code_pudl']('coal')

report_year  fuel_type_code_pudl
1994         coal                    14984.572
             gas                     10792.496
             nuclear                227983.354
             oil                      9362.194
             other                     116.737
                                       ...    
2018         coal                     9488.197
             gas                      4322.494
             nuclear                173267.161
             oil                     33836.602
             waste                     660.972
Name: fuel_cost_per_unit_burned, Length: 148, dtype: float64

In [ ]:
#the year with the highest average of fuel cost per unit delivered
usage_year = fuel_df.groupby('report_year')['fuel_cost_per_unit_delivered'].mean()
usage_year

report_year
1994       63.636060
1995       32.735269
1996     9196.705948
1997    11140.197239
1998      287.154420
1999       25.551627
2000      985.362877
2001       60.050396
2002       47.594361
2003       55.663493
2004      139.524275
2005       41.438184
2006       38.657484
2007       43.325023
2008       58.588197
2009      652.694163
2010       91.862105
2011       59.774667
2012       60.994502
2013      172.307591
2014      192.737183
2015      326.535511
2016      103.901761
2017       46.196861
2018      499.269966
Name: fuel_cost_per_unit_delivered, dtype: float64